server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_aquarium?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

aquarium-service:
  host: localhost
  port: 8080

rabbitmq:
  exchange:
    device-command: aquarium.device.command
  queue:
    device-command: aquarium.queue.device.command
  routing-key:
    device-command: device.command.#
